### PR TITLE
Multivoice CLI Similar to Gradio App

### PR DESCRIPTION
**Pull request by chigkim**
Inspired by the Gradio app, my attempt to make CLI to generate with multiple voices.
It's a combination of both podcast and emotion tabs.
Not 100% done, missing the combined spectrogram, but I just wanted to check what you guys think first.

Run: `python inference-cli.py -c samples/story.toml`
Configuration looks like this with three voices: main, town, and country.
The sample files are from vctk dataset.

```toml
model = "F5-TTS"
ref_audio = "samples/main.flac"
# If an empty "", transcribes the reference audio automatically.
ref_text = ""
gen_text = ""
gen_file = "samples/story.txt"
remove_silence = true
output_dir = "samples"

[voices.town]
ref_audio = "samples/town.flac"
ref_text = ""

[voices.country]
ref_audio = "samples/country.flac"
ref_text = ""
```

You mark the voice with [main] [town] [country] whenever you want to change voice.

```txt
A Town Mouse and a Country Mouse were acquaintances, and the Country Mouse one day invited his friend to come and see him at his home in the fields. The Town Mouse came, and they sat down to a dinner of barleycorns and roots, the latter of which had a distinctly earthy flavour. The fare was not much to the taste of the guest, and presently he broke out with [town] “My poor dear friend, you live here no better than the ants. Now, you should just see how I fare! My larder is a regular horn of plenty. You must come and stay with me, and I promise you you shall live on the fat of the land.” [main] So when he returned to town he took the Country Mouse with him, and showed him into a larder containing flour and oatmeal and figs and honey and dates. The Country Mouse had never seen anything like it, and sat down to enjoy the luxuries his friend provided: but before they had well begun, the door of the larder opened and someone came in. The two Mice scampered off and hid themselves in a narrow and exceedingly uncomfortable hole. Presently, when all was quiet, they ventured out again; but someone else came in, and off they scuttled again. This was too much for the visitor. [country] “Goodbye,” [main] said he, [country] “I’m off. You live in the lap of luxury, I can see, but you are surrounded by dangers; whereas at home I can enjoy my simple dinner of roots and corn in peace.”
```

I'd appreciate your thoughts.
Thanks!

### CODE REVIEW

**Comment by chigkim** [comment]
@SWivid, there's a probably easy answer, but any idea on how to combined spectrogram?
The process function loops through each voice tag with:
`audio, spectragram = infer(ref_audio, ref_text, gen_text, model, remove_silence)`
Right now I'm just ignoring the spectragram from infer function.
Is there a way to combine them with numpy? Or, should it just generate new spectragram based on final_wave?
`final_wave = np.concatenate(generated_audio_segments)`
Here are some additional thoughts:
Would it be possible for someone to refactor and come up with common functions that both cli and gradio app share, before they diverged too much?
Other than the fact that podcast tab only works with two voices, is there difference between Podcast and multi-style tabs on Gradio app? You should be able to achieve podcast with multi-style? They just have different way of marking voices on script, right? Am I missing something?
Thanks!

**Comment by SWivid** [comment]
Yes, maybe someone could help!
we are just focusing on developping v2 model

**Comment by SWivid** [comment]
@chigkim @jpgallegoar @JarodMica @lpscr @cocktailpeanut 
Hi there ~

We trust your submission very much, because we have limited manpower, so we may not always be able to merge in time.
So I just sent an invitation to you all to collaborate together.

Feel free just merge ! I think you are far more familiar with these modules than we are !

**Comment by JarodMica** [comment]
> @chigkim @jpgallegoar @JarodMica @lpscr @cocktailpeanut Hi there ~
> 
> We trust your submission very much, because we have limited manpower, so we may not always be able to merge in time. So I just sent an invitation to you all to collaborate together.
> 
> Feel free just merge ! I think you are far more familiar with these modules than we are !

Appreciate the trust! I don't have the knowledge to fully understand all the architectural stuff going on, but do understand the fine-tuning and training stuff generally so glad to be of help where I can.

**Comment by jpgallegoar** [comment]
Dear @SWivid. Have you explored any form of quantization of the model? I'd like to give it a shot but I need the config.json architecture file. I think it could be interesting to explore since current model is full precision 32 bits. Maybe Q8 retains quality being much faster.

**Comment by SWivid** [comment]
Hi @jpgallegoar , we have seen through some existing tools to do quantization e.g. gptq, awq, though we felt a little at a loss since we are new to this, and these tools seems mostly take text llm for usage example.
If you are interested in it, what kind of config.json we could help provide~

**Pull request merged**
