### PR TITLE
Add Voice Chat feature

### PR DESCRIPTION
**Pull request by jpgallegoar**
@SWivid This one I will not merge myself because I need your confirmation. This adds an AI Voice Chat feature using LLM Qwen2.5-3B (very fast), 3gb only, but needs pip install transformers_stream_generator. 

I hope you like it.

Also I added it to the README.md features section and to requirements.txt

### CODE REVIEW

**Comment by jpgallegoar** [comment]
It fails some quality checks but the code works well, I tested it a lot. I will make it pass the tests tomorrow after commit is merged

**Comment by SWivid** [comment]
@jpgallegoar Hi, very cool chat!

I just test it, may need few tweaks with your help:
1. will the ref_text saved and not calling asr pipeline to do transcription again if not ref_audio not changed? may take it as a func to utils_infer.py as it's widely appliable for all other apps
2. may need extra loading time and gpu memory for those just want do basic tts, maybe we could add a button to chat (load in qwen2.5, whisper, and show the interface then), it can be also helpful if the switch between F5/E2 will offload the counterpart.

Greetings.

**Comment by jpgallegoar** [comment]
Thank you for the inputs, I also thought about the extra loading time. I will look into it and update.

**Comment by SWivid** [comment]
@jpgallegoar Phoneme-level alignment is just what we were to abandon, check https://aka.ms/e2tts/
we'll possibly go like:
1. Multilanguage
2. Model structure exploration addressing long sample generation

> Longer context length thanks to a dataset with longer audios & emotional controllability using emotion-specific tokens

Mainly for data scarcity as we all know, will keep eyes on it

**Comment by jpgallegoar** [comment]
Thank you for your answer. I am very interested in future developments.

**Pull request merged**
