### PR TITLE
Adding support for F5-small models, sharing a Hindi checkpoint trained from scratch and adding NFE steps in inference scripts

### PR DESCRIPTION
**Pull request by rumourscape**
In this PR I am contributing three things as given in title.

### CODE REVIEW

**Comment by thesandi99** [comment]
Oh hindi is nice how much hour you train model , becuas im train 60H and is not result like your's model and wht setting

**Comment by rumourscape** [comment]
> Oh hindi is nice how much hour you train model , becuas im train 60H and is not result like your's model and wht setting

I have trained the small config model with about 80 hrs of data for 2.5 million steps.

**Comment by SWivid** [comment]
Thanks a lot!
Will check after #518 , which enables using yaml for better config

**Comment by Aunali321** [comment]
@rumourscape Hi, Can you share training code for this model?

**Comment by thesandi99** [comment]
> I tested the model and it sounds trash

actually is better in 80H training

**Comment by rumourscape** [comment]
> I tested the model and it sounds trash

You clearly haven't used it properly then. The ref_audio must be in Hindi and the ref_text & gen_text must be in Devanagari script. I have showed this model to many colleagues and they all believe that this is probably the current SOTA for Hindi TTS.

**Comment by rumourscape** [comment]
> @rumourscape Hi, Can you share training code for this model?

I have used the same training script as given in the F5 repo. The only change I made was to skip the preprocess step and directly plug in the Huggingface datasets using the HFDataset class.

**Comment by SWivid** [comment]
@rumourscape yes, busy currently, will modified as mentioned in #591 
will come back and add this feature asap

**Comment by sudeep333** [comment]
It would be great if you add Hindi language support. Thank you in advance.

**Comment by SWivid** [comment]
Hi @rumourscape , feel free to check the update
Thanks again for sharing and adding Hindi model~

**Comment by rumourscape** [comment]
> Hi @rumourscape , feel free to check the update 

Looks good!

**Pull request closed without merging**
