### PR TITLE
Add updated JA model

### PR DESCRIPTION
**Pull request by JarodMica**
Updated JA model after training for about 4 weeks on the same dataset.

### CODE REVIEW

**Comment by ZhikangNiu** [comment]
@JarodMica In the Japanese written language, there are three types of characters: Hiragana, Katakana, and Kanji. I noticed that all three types are present in Emilia. Could you share the functions you use to process the text? And do you know of any publicly available Japanese TTS test datasets?

**Comment by SWivid** [comment]
Appreciated~

**Comment by JarodMica** [comment]
> @JarodMica In the Japanese written language, there are three types of characters: Hiragana, Katakana, and Kanji. I noticed that all three types are present in Emilia. Could you share the functions you use to process the text? And do you know of any publicly available Japanese TTS test datasets?

[prepare_emilia_ja copy.zip](https://github.com/user-attachments/files/18177879/prepare_emilia_ja.copy.zip)

This was the script I used to prepare Emilia and Galgame - it's pretty messy as it was modified with a few shot prompting in ChatGPT but either wise, works.  Normalized to kanji --> hiragana but kept katakana where it was already being used.

The biggest public one I know is: https://huggingface.co/datasets/reazon-research/reazonspeech and then I learned of galgame from someone here.  Only issue is that they're 16khz, so galgame for example I had to recreate and resample the DS to 24KHz which is what I trained on.

**Comment by hopto-dot** [comment]
@JarodMica How good is the new model? Would you be able to provide samples?

**Pull request merged**
