### PR TITLE
new update gradio finetune

### PR DESCRIPTION
**Pull request by lpscr**
@SWivid  just another great update and fix some stuf 

first add create vocan from the dataset and you can see

image

support now calculate settng multi gpu in train find all gpu memory

add system info see cpu and gpu 

image

**question** 

can you please tell me only one part need fix in caluclate epochs 
from example see this 

i use 5 min 38 sample i get epoch **133235** ! this correct 

samples : 38  small i know 

```
total_hours = 0.0833
mel_hop_length = 256
mel_sampling_rate = 24000

# target
wanted_max_updates = 1000000

# train params
gpus =1
frames_per_gpu = 3200
grad_accum = 1
```

### CODE REVIEW

**Comment by lpscr** [comment]
@SWivid also about the vocab new from dataset 
i think be good to extend with vocab for Emilia_ZH_EN_pinyin 
for example if there is new symbols not in let to add 
this from train from the scratch wha you think ? 
like this keep all symbols and add new

**Comment by SWivid** [comment]
@lpscr 
`wanted_max_updates = 1000000` is just up to user's need
(say, what ever you want, hard to tell which is better, cuz every use different dataset with different size)
the script we put there is just for calculation

It is a good idea to extend the vocab, and you could actually reuse weights in pretrained model ckpt for those trained indexs of vocab, though this operation needs some engineering stuff.

I see that you fix it as `vocab_size = 2545`, thought better to read file, and dynamically count for number of rows like
https://github.com/SWivid/F5-TTS/blob/40b2c851c114635b233909c3209a9739686d6974/model/utils.py#L128
cuz we will probably release new pretrained models with different vocab map

**Comment by lpscr** [comment]
@SWivid understand so user must put manual this option then **epochs** to dont confuse 

ok maybe i put only **extend** because i think if someone train the model from the scratch so with have a lot vocab
to finetune after with other langauge

**IDEA :**
just idea let say i train new language checkpoint export fintune.pt and this language it's use symbols you have also inside but dont  have weight 
**Emilia_ZH_EN_pinyin** because use English  and Chinese symbols but the vocab.txt have other symbols langauges

can take **finetune** + **pretrain** models merge weight ? 
so i have new model  with
Chinese + English  + new language fintune
it's possible ? 

last  question i want to add option for fp16 this speed up the fintune ? or maybe curse or not need ?
`accelerate launch --mixed_precision=fp16 train.py`

**Comment by SWivid** [comment]
@lpscr fp16 or bf16 depends on your gpu
generally we could set fp16 with `accelerate config`
or `accelerate launch --mixed_precision=fp16 train.py`

> can take finetune + pretrain models merge weight ?

maybe not that way haha, what i mean is just extend the vocab and along with the nn.embedding dimension in model

**Comment by lpscr** [comment]
> @lpscr fp16 or bf16 depends on your gpu generally we could set fp16 with `accelerate config` or `accelerate launch --mixed_precision=fp16 train.py`
> 
> > can take finetune + pretrain models merge weight ?
> 
> maybe not that way haha, what i mean is just extend the vocab and along with the nn.embedding dimension in model

ok i want to try this working also with finetune problem with len i mean because change ? i have code for extend  embedding
if i do this i don't lost **Chinese** and **English** , and with new langauge ?
if yes i need to test test right today !

**Comment by SWivid** [comment]
> Will the model then be able to speak three languages (including the newly finetuned one)?

but you need to have Chinese and English included in finetuning dataset to avoid catastrophic forgetting
it needs careful tweak, to include new language ability while keep the original ones

**Comment by lpscr** [comment]
> > Will the model then be able to speak three languages (including the newly finetuned one)?
> 
> but you need to have Chinese and English included in finetuning dataset to avoid catastrophic forgetting it needs careful tweak, to include new language ability while keep the original ones

@SWivid  ah ! ok i know this i have test already ... and yes this happend , but if you use dataset working fine i test also
thats i say if possible to merge 2 models weight .

**Comment by SWivid** [comment]
> if possible to merge 2 models weight . so not need the dataset English , Chinese ...

not sure if will work.
a more possible solution is to do llama-adapter finetuning.

**Comment by lpscr** [comment]
@SWivid update add mixed_precision option

image

**Comment by x4080** [comment]
Hi, I'm trying to train and before that in the 1st tab (transcribe data), I click random sample, the text appear but the audio next to it is empty (the time length is 0:00) so when I click play/download it won't work

my metadata.csv is
```
audio1|hello what is your name
...
```
Is this expected ? Or I did something wrong ? I put audio1.wav inside my_speak_char/wavs

**Pull request merged**
