### PR TITLE
Replicate API Badge Added

### PR DESCRIPTION
**Pull request by zsxkib**
# 🎉 F5-TTS Now on Replicate! 🚀

Hey F5-TTS team,

First off, great work on the model. The voice cloning capabilities are really impressive.

I've set up F5-TTS on Replicate to make it easier for people to try out and potentially use in their projects:

https://replicate.com/sjtu/f5-tts

## What's new:

- Added a Replicate badge to the README
- Set up a web demo and API on Replicate

The Replicate page has a simple interface for testing the model, similar to your Hugging Face space. It also provides API access, which could be handy for developers wanting to integrate F5-TTS into their applications.

## Technical notes:

I've prepared `predict.py` and `cog.yaml` files for the Replicate setup. These aren't included in this PR, but I can add them here or in a separate PR if you're interested in the implementation details.

Let me know if you have any questions about the Replicate integration or if you'd like any changes made to the setup.

Thanks for your work on F5-TTS and for making it open source!

- Sakib @ Replicate

### CODE REVIEW

**Comment by SWivid** [comment]
Hi @zsxkib ~

Thanks for your recognition of our work.
There's only a minor tweak to be made. You might just relink to to our lab's github page https://github.com/X-LANCE

Thanks again.

**Comment by SWivid** [comment]
> Hi @zsxkib ~
> 
> Thanks for your recognition of our work. There's only a minor tweak to be made. You might just relink to to our lab's github page https://github.com/X-LANCE
> 
> Thanks again.

Ah, I also notice that the replicate space is running on a old version of gradio_app in our repo.
Not sure if you could synchronize or not, as the github repo noted in replicate page pointing to a third party implementation

**Comment by zsxkib** [comment]
Hi @SWivid ~

Thanks for your feedback on the Replicate integration. I want to make sure I understand your requests correctly:

1. You mentioned: 
   > There's only a minor tweak to be made. You might just relink to to our lab's github page https://github.com/X-LANCE
   
   Could you elaborate on what you mean by this? I'm not sure where this relink should occur or what exactly needs to be changed. Any additional details would be helpful.

2. Regarding the version sync:
   You noted that the Replicate space is using an old version of the gradio_app from your repo. 
   - Should I just fetch and pull from upstream to get the latest version? 
   - If not, could you point me to the location of the most up-to-date official implementation and current gradio_app in your repository?

Once I understand what you're asking for, I'll be happy to make those changes to accurately represent your work on Replicate

Thanks for your patience, and I look forward to your clarification ☺️

**Comment by SWivid** [comment]
Hi @zsxkib 
1. The affiliation currently links to a irrelevent place https://github.com/sjtu , while it should be https://github.com/X-LANCE
2. If i got it right, the space is under https://replicate.com/sjtu/f5-tts/versions relately to https://github.com/cuuupid/cog-f5-tts which is updated 2 days ago, and we have just changed to more robust chunk inference method.
3. Also i got in Replicate website a message that we could not directly leverage the space to do inference unless register and add a payment method; which is greatly against our concept

**Comment by zsxkib** [comment]
Hi @SWivid,

Thanks for clarifying. I want to address each of your points:

1. Affiliation link and Replicate username/organisation:

   I apologise for the incorrect link. I'll change it from https://github.com/sjtu to https://github.com/X-LANCE right away, so the model will live under replicate.com/x-lance/f5-tts. 

   About the Replicate username 'sjtu': Let me clarify how Replicate handles usernames and organisations:

   - Usernames on Replicate are directly linked to GitHub accounts. When you sign up, Replicate adopts your GitHub username.
   - Organisations, on the other hand, can be named anything and aren't tied to a specific GitHub account. They're similar to replicate.com/openai, where multiple users can contribute.

   We used 'sjtu' (Shanghai Jiao Tong University) as an organisation name since we weren't sure which specific GitHub account to attribute the model to. We have a couple of options moving forward:

   a) We can keep it as an organisation and rename it to anything you prefer (e.g., 'x-lance', 'f5-tts-team', etc.).
   b) We can attribute it to a specific GitHub user who has signed up for Replicate, in which case it would use that person's GitHub username.

   What would you prefer? Just let us know, and we'll update both the affiliation link and the Replicate username/organisation accordingly.

2. Version update:
   You're right that the current version is based on https://github.com/cuuupid/cog-f5-tts. We'd love to update it with your latest robust chunk inference method. This will need to be done manually by us. I assume this repo has the new updates? (just checking 😄)

   The reason the model on Replicate (https://replicate.com/sjtu/f5-tts) links to cuuupid's repo is that it contains the Replicate-specific files: `predict.py` and `cog.yaml`. These two files are all you need to create an API endpoint, which is what Replicate's backend uses to run the model. We can definitely update these to work with your latest version.
   
   When we normally create a PR to a new open source model we add the files `predict.py` (code to run model), `cog.yaml` (code to set up machine learning environment), and edit the `README.md` (replicate badge pointing to WebUI and API) - but in this case, for this PR we have only edited the `README.md`.

3. Payment requirement:
   I completely understand your concern about the payment requirement. Let me explain how Replicate works and how it compares to platforms like Hugging Face Spaces:

   - Replicate is open-source first. All the code, including the model implementation, remains completely open and free.
   - The key difference from Hugging Face Spaces is who pays for computation. On Replicate, end-users pay for GPU/inference costs, not the model creators.
   - This means you, as researchers, don't have to bear the costs of running the demo. With popular models, these costs can become significant.
   - Replicate uses a cold-booting system that dynamically spins up and shuts down instances, which helps keep costs low for users.
   - Anyone can still run the model for free by using the open-source code on their own hardware. The `predict.py` and `cog.yaml` files make it easy for developers to set up their own API endpoints, just like we do at Replicate (that's what we do on our backend).

Our goal at Replicate is to support open-source projects like yours. We want to showcase your work in a way that aligns with your goals while making it accessible to developers and researchers.

Let me know your thoughts on these points. We're happy to make any necessary adjustments to ensure we're representing your work accurately and in line with your vision ✨

cc @cuuupid

**Comment by cuuupid** [comment]
@SWivid I've just adjusted the organization to point to X-Lance instead. Could you double check that everything looks good? Happy to change logo, images, etc. anything else to keep branding streamlined for you.

https://replicate.com/x-lance

I'll work on folding in the chunking changes -- thanks for improving this!

**Comment by SWivid** [comment]
Hi @zsxkib @cuuupid ,

All modification is just reflected in main branch of this repo.
I was just wondering if Replicate would keep with up-to-date version of inference script, or it needs manual tweak for each update which is wasting your time unnecessarily, though it would just be fine to update with key new features.
Or if you would mind to have a notification links to Replicate at a lower place in this repo with proper appreciation ?

**Comment by zsxkib** [comment]
Hey @SWivid,

I noticed you closed the PR, and I totally get it if you're not interested in the Replicate integration. No worries at all if that's the case!

Thanks for the feedback! Just wanted to quickly address your points:

- Keeping things up-to-date: Yep, we'll manually update the Replicate version (predict.py + cog.yaml) to match your repo. We're happy to do this, just like folks do for Hugging Face spaces

- README placement: Totally flexible on this. The badge can go wherever you think is best. Next to other platforms makes sense for visibility, but we're cool with wherever you prefer

- PR scope: Right now it's just the README badge. We normally add the `predict.py + cog.yaml` files but they're not ready yet and when they are we'll open a PR for them (these files mean that someone can just do `cog predict -i ...` and run the model in a docker container locally with no setup/installs/etc.)

We're pretty excited about F5-TTS and would love to help promote it, but no pressure at all. If you're not feeling the Replicate integration, that's totally fine

Btw we're planning to add finetuning/training API support on Replicate soon, which could be neat for F5-TTS users

Let me know if you have any questions or if you want to chat more about this. If not, no worries!

Cheers,
Sakib

**Pull request closed without merging**
