### PR TITLE
gradio_finetune

### PR DESCRIPTION
**Pull request by lpscr**
Hi @SWivid  , I created a Gradio interface for fine-tuning. 

There's only one part I need to change in the training settings. Are there any good default settings I can use?

Tab transcribe 
    a) You can simply place audio files in data/project_name/dataset . in tab transcribe check user**

```
my_speak/
│
├── dataset/
│   ├── audio1.wav
     └── audio2.wav
```

    b) Or you can just upload audio files directly in Gradio. In the Transcribe tab, uncheck the "user" option.

Tab preparing data
You can preparing data in second tab : You can place audio files in data/project_name/wavs and include a metadata.csv file. If you complete             the first step, there's no need to place anything else because the transcription will be created automatically.

```
my_speak/
│
├── wavs/
│   ├── audio1.wav
│   └── audio2.wav
│
└── metadata.csv

format metadata.csv
audio1|text1
audio2|text2
audio3|text3
```

Tab train
you change the setting and click start train go to terminal to setting the **wandb**

here how look like

image
image
image

here a video in action

https://github.com/user-attachments/assets/8b6aed94-1e4a-495e-af92-595c2c5cad50

### CODE REVIEW

**Comment by nitinmukesh** [comment]
@lpscr 

You are a Genius.

**Comment by SWivid** [comment]
Hi @lpscr , thanks for PR ~
Not sure if we just need gradio to do everything, cuz finetuning is also computing-resource consuming,
and from what I saw it doesn't seem to be done very often in other projects with gradio for finetuning (though probably for those relatively mature product).

As the project is far from complete, you might want to start a discussion board, provide a link to your repo and also with a gradio finetune tutorial (might be more visible to others). Received good feedback, we would be very happy to incorporate this feature ~

**Comment by lpscr** [comment]
"Thank you, @SWivid! Your repo is amazing this best tts ever see  as it is, and I appreciate your feedback. I understand your concerns regarding the resource consumption of fine-tuning with Gradio.

I created a Gradio interface for fine-tuning to make it user-friendly and accessible for beginners, as well as to help the community."

**Comment by cocktailpeanut** [comment]
@SWivid First of all, really appreciate giving us F5-TTS, I can see myself using this everyday, and have been telling everyone to use this because it's so good (I'm the creator of pinokio.computer). And @lpscr this is so great, thank you for building this.

As for the UI issue, there are tons of finetuning open source projects that use Gradio, and especially since F5-TTS itself is an open source project i can't think of any other way that's better fit than Gradio. The reason is the gradio interface is so standardaized among AI devs that anyone can easily contribute once released.

I don't think Gradio adds any resource consumption on top of whatever script you're running underneath, especially with the latest version that uses server side rendering.

Some examples gradio apps that do finetuning/training and they work great. 

1. Llamafactory: https://github.com/hiyouga/LLaMA-Factory
2. Kohya_ss: https://github.com/bmaltais/kohya_ss
3. Fluxgym: https://github.com/cocktailpeanut/fluxgym
4. Applio: https://github.com/IAHispano/Applio

That said, if you don't want Gradio, that's fine but I do think we at least need a UI for doing this easily, having a UI will allow more contributions. Even if you don't like Gradio, I don't think it would hurt to have a Gradio UI at least until you have an implementation done with whatever framework you want.

**Comment by SWivid** [comment]
Hi there ~
@cocktailpeanut Thanks for the reference to projects using Gradio, and your recognition to our efforts.
And I just saw @lpscr get the dicussion board with this tutorial #125 regarding to the usage of `finetune_gradio.py`, we will just merge and add a link to #143 in README.md

**Comment by cocktailpeanut** [comment]
@SWivid Thank you! Just tested and made a slight update to allow uploading multiple audio clips. Please check the PR https://github.com/SWivid/F5-TTS/pull/147

**Pull request merged**
