### PR TITLE
add in gradio finetune 8bit value fix some stuff and add new transcripe into easy  

### PR DESCRIPTION
**Pull request by lpscr**
@SWivid hi i make some new fix update
and a add 8bit , and also i add in utlis infer new function for get easy transcripe 
also fix sime values

### CODE REVIEW

**Comment by SWivid** [comment]
Yes, thanks!

**Comment by lpscr** [comment]
@SWivid Yes, I was sick the last few days :( , but I’m finally better now !! , so I can focus on some things here.

what about to load data for hugging face.  arrow?
like this 
new_great_1

also i wonder about the bigvgan ?any news i try finetune last days and like i say results in my case very good quality

**Comment by SWivid** [comment]
.arrow loading is great, an easy to understand and easy to use designed ui is the key for than while the loading stuff behind is straightforward

bigvgan is good at quality though tend to produce less diverse output to some extend, we can say it's good but still not perfect a vocoder.
So in general, finetuning on vocos or bigvgan both ok.

**Comment by justinjohn0306** [comment]
@lpscr I can't test the model during the training, got this msg: Traceback (most recent call last):
  File "E:\Programs\anaconda3\envs\f5-tts\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "E:\Programs\anaconda3\envs\f5-tts\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\Programs\anaconda3\envs\f5-tts\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "E:\Programs\anaconda3\envs\f5-tts\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "E:\Programs\anaconda3\envs\f5-tts\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\Programs\anaconda3\envs\f5-tts\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "E:\Programs\anaconda3\envs\f5-tts\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "E:\Programs\anaconda3\envs\f5-tts\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "E:\REPOS\F5-TTS\src\f5_tts\train\finetune_gradio.py", line 1224, in infer
    tts_api = F5TTS(
  File "E:\REPOS\F5-TTS\src\f5_tts\api.py", line 52, in __init__
    self.load_ema_model(
  File "E:\REPOS\F5-TTS\src\f5_tts\api.py", line 82, in load_ema_model
    self.ema_model = load_model(
  File "E:\REPOS\F5-TTS\src\f5_tts\infer\utils_infer.py", line 256, in load_model
    model = load_checkpoint(model, ckpt_path, device, dtype=dtype, use_ema=use_ema)
  File "E:\REPOS\F5-TTS\src\f5_tts\infer\utils_infer.py", line 178, in load_checkpoint
    if torch.cuda.is_available() and torch.cuda.get_device_properties(device).major >= 6
  File "E:\Programs\anaconda3\envs\f5-tts\lib\site-packages\torch\cuda\__init__.py", line 466, in get_device_properties
    device = _get_device_index(device, optional=True)
  File "E:\Programs\anaconda3\envs\f5-tts\lib\site-packages\torch\cuda\_utils.py", line 34, in _get_device_index
    raise ValueError(f"Expected a cuda device, but got: {device}")
ValueError: Expected a cuda device, but got: cpu

**Comment by SWivid** [comment]
@justinjohn0306 thanks~
fixed in last commit 84db0029ce822f75593ba66997cc687327658e71

**Pull request merged**
